server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://userdb:5432/userdb
    username: codeevo
    password: codeevo_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

jwt:
  secret: "c2VjdXJlLWp3dC1zZWNyZXQta2V5LWZvci1jb2RlZXZvLW1vbm9saXRoLWFwcC0yMDI0"
  expiration: 86400000
